### PR TITLE
Import ansible module_utils before others.

### PR DESCRIPTION
**Pull request by PriceChild**
Fixes "AttributeError: 'module' object has no attribute 'fromtimestamp'" error with ansible 2.0.1.0

Think this was introduced with 0b92abaf67de53349bb4d2733f49750d9a4d8277 where datetime was imported in that module.

It'd probably be a better solution to import individual functions from module_utils as needed, but just reordering fixes the immediate issue?

### CODE REVIEW

**Comment by PriceChild** [comment]
Fantastic, thanks!
